server:
  port: 8082
spring:
  application:
    name: consumer
dubbo:
  application:
    name: ${spring.application.name}
    qos-port: 33333
  registry:
    address: zookeeper://10.0.0.8:2181,10.0.0.8:2182,10.0.0.8:2183